### ISSUE TITLE
it's not work bro

### ISSUE THREAD

**Issue by sabri-zaki** [Bhai4You/Bash-Locker#1]
it's just show your name 
and it's batter to mack it professional and remove your name from it because I don't want when I run my script your name show up each time and thanks for your efforts

**Comment by termux4me** [comment]
زاكي هذلسكربت فه ثغره

**Comment by sabri-zaki** [comment]
وش هي الثغرة اخي

**Comment by sabri-zaki** [comment]
لا اعرف

**Comment by termux4me** [comment]
روح للمسنجر

**Comment by termux4me** [comment]
تلقاها فالمساج بصح متحلبهش بيها

**Comment by sabri-zaki** [comment]
Hhhhh ok

**Comment by Bhai4You** [comment]
install bash-obuscato

> it's just show your name
> and it's batter to mack it professional and remove your name from it because I don't want when I run my script your name show up each time and thanks for your efforts


Code :
pkg install nodejs
npm install -g bash-obfuscate
bash-obfuscate $file -o /sdcard$output
