### ISSUE TITLE
you have big issues

### ISSUE THREAD

**Issue by termux4me** [Bhai4You/Bash-Locker#2]
here is requirement.sh file after i unencrypte 
i got all the script this means that we didn't do a thing
clear
apt update -y
apt upgrade -y
pkg install nodejs -y
apt install figlet -y
apt install curl -y
npm install -g bash-obfuscate
clear

**Comment by 0xS0l0** [comment]
apt update && apt upgrade
pkg install nodejs
npm install -g bash-obfuscate

bash-obfuscate $file -o /sdcard$output

**Comment by termux4me** [comment]
as you can see bash locker code can be reversed

**Comment by 0xS0l0** [comment]
👍
